import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AppInitiazor {
    private JButton modalitaDipendenteButton;
    private JButton modalitaResponsabileButton;
    public JPanel panelMain;

    public AppInitiazor() {

        modalitaDipendenteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                JFrame frame = new JFrame("Modalità Dipendente");
                frame.setContentPane(new ModalitaDipendente().panelDipendente);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);

            }
        });

        modalitaResponsabileButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame frame = new JFrame("Modalità Responsabile");
                frame.setContentPane(new ModalitaResponsabile().panelResponsabile);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new BorderLayout(0, 0));
        panelMain.setPreferredSize(new Dimension(400, 400));
        panelMain.setRequestFocusEnabled(false);
        final JSeparator separator1 = new JSeparator();
        panelMain.add(separator1, BorderLayout.WEST);
        modalitaResponsabileButton = new JButton();
        modalitaResponsabileButton.setText("Modalità Responsabile");
        panelMain.add(modalitaResponsabileButton, BorderLayout.CENTER);
        modalitaDipendenteButton = new JButton();
        modalitaDipendenteButton.setText("Modalità Dipendente");
        panelMain.add(modalitaDipendenteButton, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
